build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
labels:
  org.opencontainers.image.source: "https://swdevtfs.fan2customer.com/Ublion/AI%20EnergyAdvisor/_git/saldox-ha-addons"
  org.opencontainers.image.licenses: "MIT"
